### ISSUE TITLE
Incorrect results for Windows Terminal

### ISSUE THREAD

**Issue by dropsonic** [jamestalmage/supports-hyperlinks#7]
Starting with v1.4, Windows Terminal supports embedded hyperlinks.
However, `supports-hyperlinks` returns `false` for this terminal.

As a workaround, I set the environment variable `FORCE_HYPERLINK`, and everything started working fine.

It happens because there is a piece of code that disables hyperlink support everywhere on Windows (which is not correct):

```js
if (process.platform === 'win32') {
    return false;
}
```

It is possible to understand that we're running in Windows Terminal by checking `env.WT_SESSION` existence; however, it is not so easy to get the actual version of the terminal. See https://github.com/microsoft/terminal/issues/1040 for more details.

**Comment by jamestalmage** [comment]
PR Welcome.

**Comment by dropsonic** [comment]
@jamestalmage it is not possible to properly implement it until microsoft/terminal#1040 is completed.

**Comment by abhijit-hota** [comment]
Windows Terminal issues have been troubling me more than they should. I was finding ways to know the version number as you said. 

One way I thought of was to execute `wt -v` (`wt` is included in the `Path`!). 
But to my disappointment, it opened up an alert window rather printing it.

![image](https://user-images.githubusercontent.com/8116174/101306635-71fd1680-386b-11eb-8e75-bbf8e65e9ef6.png)

Now we can go ahead and file another issue about this but I thing a more elegant way for them will be to solve [microsoft/terminal#1040](https://github.com/microsoft/terminal/issues/1040).

**Comment by abhijit-hota** [comment]
Right now, can we use `TERM_PROGRAM` and `TERM_PROGRAM_VERSION` to detect VSCode?

**Comment by abhijit-hota** [comment]
I was finding ways to know the version number as you said. 

One way I thought of was to execute `wt -v` (`wt` is included in the `Path`!). 
But it opened up an alert window rather than printing it.

[I asked why and they said the reason](https://github.com/microsoft/terminal/issues/5001#issuecomment-739645579)

![image](https://user-images.githubusercontent.com/8116174/101306635-71fd1680-386b-11eb-8e75-bbf8e65e9ef6.png)

**Comment by Richienb** [comment]
> One way I thought of was to execute wt -v (wt is included in the Path!).

![image](https://user-images.githubusercontent.com/29491356/103962521-02f14580-51bc-11eb-97fd-8c1ed4c77851.png)

**Comment by Richienb** [comment]
Right now, [this is the best way I could find to do it](https://github.com/Richienb/is-windows-terminal).

**Comment by abhijit-hota** [comment]
But we also want the version of Windows Terminal, don't we?

**Comment by Richienb** [comment]
@abhijit-hota Perhaps we can get the version from the Windows Store package.

**Comment by dropsonic** [comment]
According to [Microsoft](https://github.com/microsoft/terminal/issues/1040#issuecomment-756953154), there is no need to check the exact version of the terminal.
I've created a PR: #8
